version: 2
updates:

  # Maintain dependencies for go in root
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"


  # Maintain dependencies for go tools
  - package-ecosystem: "gomod"
    directory: "/hack/internal/tools"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"

  # Maintain npm dependencies for web
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"

  # Maintain npm dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"

  # Maintain npm dependencies for ui
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 10

  # Maintain Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
