# config for local dev env
debug: true
log:
  level: debug

database:
  driver: sqlite3
  dsn: "file:matrixhub_dev.db?cache=shared&_foreign_keys=1"
  accessType: readwrite
  maxOpenConns: 100
  maxIdleConns: 10
  connMaxLifetimeSeconds: 3600
  connMaxIdleSeconds: 1800

apiServer:
  port: 3001
